spring:
  application:
    name: myaccount
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myaccount
    username: root
    password:
  jpa:
    generate-ddl: true
    show-sql: true
#    hibernate:
    ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
currency:
  converter:
    url: https://api.exchangeratesapi.io/latest?base=